theme: jekyll-theme-minimal
title: Minautor
description: An Arduboy game
logo: https://raw.githubusercontent.com/maxime-hanicotte/Minautor/master/minautor.jpg
show_downloads: false
google_analytics: UA-143672565-1
