theme: jekyll-theme-minimal
title: Minautor
description: An Arduboy game
logo: https://avatars2.githubusercontent.com/u/12615544?s=460&v=4
show_downloads: false
google_analytics: [Your Google Analytics tracking ID]
